### ISSUE TITLE
Pass service, stream and index to external filter functions

### ISSUE THREAD

**Issue by nbclark** [doubledutch/StroomData#32]
Would be nice if I didn't have to store data from inputs locally and could instead store the stream and index to later reference. Would be preferable to be passed as headers like:

X-SERVICE-NAME, X-STREAM-NAME, X-STREAM-INDEX

**Comment by kasperjj** [comment]
This has been added to v0.1.7. The header names are X-Stroom-Service, X-Stroom-Index and X-Stroom-Partition ... stream name has not been added for now, since it's a bit less straight forward depending on wether it's a local or remote stream!
